### ISSUE TITLE
time killing

### ISSUE THREAD

**Issue by herrtao** [AdrienGuille/TOM#4]
how long it will take for a processing? When I tried the test dataset, the computer is running all the time!!!
My computer is Intel i5@3.2GHz, with 8GB RAM. Can we speed up?

**Comment by AdrienGuille** [comment]
Hi,

Without any details, I can't help you.
If you're simply running the example, then you can comment out the lines that run the code to estimate the optimal number of topics (which takes a lot of time). It will infer the topics in a matter of seconds.

Adrien

**Comment by crownpku** [comment]
Hi, Adrien.
I got stuck at `topic_model.infer_topics(num_topics=k)` in TOM.ipynb.
I have tried to change k to be smaller or use the LDA instead of NMF, but my computer still got stuck there, running for more that 30 minutes and got no result yet.
I see your comment that "It will infer the topics in a matter of seconds", which seems not to be the case here.... Would you please give some help here? Thanks!
